/****************************************************************************
**
** Metadata for FooBarOcx generated by dumpcpp v5.12.6 using
** V:\develop\qt\5.12.6\msvc2017_64\bin\dumpcpp.exe -o foobarocx -n FooBarOcx ../build/vc80/activex/FooBarOcx.tlb
** from the type library ..\build\vc80\activex\FooBarOcx.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_FOOBAROCX_NOINLINES
#include "foobarocx.h"

using namespace FooBarOcx;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[23];
    char stringdata0[193];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 14, 0),
QT_MOC_LITERAL(1, 15, 11, 0),
QT_MOC_LITERAL(2, 27, 4, 0),
QT_MOC_LITERAL(3, 32, 9, 0),
QT_MOC_LITERAL(4, 42, 0, 0),
QT_MOC_LITERAL(5, 43, 4, 0),
QT_MOC_LITERAL(6, 48, 6, 0),
QT_MOC_LITERAL(7, 55, 4, 0),
QT_MOC_LITERAL(8, 60, 4, 0),
QT_MOC_LITERAL(9, 65, 15, 0),
QT_MOC_LITERAL(10, 81, 4, 0),
QT_MOC_LITERAL(11, 86, 6, 0),
QT_MOC_LITERAL(12, 93, 4, 0),
QT_MOC_LITERAL(13, 98, 4, 0),
QT_MOC_LITERAL(14, 103, 8, 0),
QT_MOC_LITERAL(15, 112, 15, 0),
QT_MOC_LITERAL(16, 128, 7, 0),
QT_MOC_LITERAL(17, 136, 14, 0),
QT_MOC_LITERAL(18, 151, 4, 0),
QT_MOC_LITERAL(19, 156, 6, 0),
QT_MOC_LITERAL(20, 163, 6, 0),
QT_MOC_LITERAL(21, 170, 5, 0),
QT_MOC_LITERAL(22, 176, 15, 0)
    },
    "FooBarOcx::Foo\0Interface 0\0IFoo\0exception\0\0code\0source\0disc\0help\0propertyChanged\0"
    "name\0signal\0argc\0argv\0SayHello\0FooBarOcx::IFoo\0control\0FooBarOcx::Bar\0IBar\0"
    "GetFoo\0IFoo**\0ppFoo\0FooBarOcx::IBar\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_FooBarOcx__Foo[] = {

 // content:
    7, // revision
    0,  // classname
    1, 14, // classinfo
    4, 16, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 2, 

// signal: name, argc, parameters, tag, flags
    3, 4, 36, 4, 5,
    9, 1, 45, 4, 5,
    11, 3, 48, 4, 5,

// slot: name, argc, parameters, tag, flags
    14, 0, 55, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void,

    0 // eod
};

const QMetaObject Foo::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_FooBarOcx__Foo, 0, 0, 0 }
};

void *Foo::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "FooBarOcx::Foo"))
        return static_cast<void*>(const_cast<Foo*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_FooBarOcx__IFoo[] = {

 // content:
    7, // revision
    15,  // classname
    0, 0, // classinfo
    4, 14, // methods
    1, 54, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 34, 4, 5,
    9, 1, 43, 4, 5,
    11, 3, 46, 4, 5,

// slot: name, argc, parameters, tag, flags
    14, 0, 53, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void,

 // properties: name, type, flags
    16, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IFoo::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_FooBarOcx__IFoo, 0, 0, 0 }
};

void *IFoo::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "FooBarOcx::IFoo"))
        return static_cast<void*>(const_cast<IFoo*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_FooBarOcx__Bar[] = {

 // content:
    7, // revision
    17,  // classname
    1, 14, // classinfo
    4, 16, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 18, 

// signal: name, argc, parameters, tag, flags
    3, 4, 36, 4, 5,
    9, 1, 45, 4, 5,
    11, 3, 48, 4, 5,

// slot: name, argc, parameters, tag, flags
    19, 1, 55, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, 0x80000000 | 20, 21,

    0 // eod
};

const QMetaObject Bar::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_FooBarOcx__Bar, 0, 0, 0 }
};

void *Bar::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "FooBarOcx::Bar"))
        return static_cast<void*>(const_cast<Bar*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_FooBarOcx__IBar[] = {

 // content:
    7, // revision
    22,  // classname
    0, 0, // classinfo
    4, 14, // methods
    1, 56, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 34, 4, 5,
    9, 1, 43, 4, 5,
    11, 3, 46, 4, 5,

// slot: name, argc, parameters, tag, flags
    19, 1, 53, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, 0x80000000 | 20, 21,

 // properties: name, type, flags
    16, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IBar::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_FooBarOcx__IBar, 0, 0, 0 }
};

void *IBar::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "FooBarOcx::IBar"))
        return static_cast<void*>(const_cast<IBar*>(this));
    return QAxObject::qt_metacast(_clname);
}

