/****************************************************************************
**
** Namespace FooBarOcx generated by dumpcpp v5.12.6 using
** V:\develop\qt\5.12.6\msvc2017_64\bin\dumpcpp.exe -o foobarocx -n FooBarOcx ../build/vc80/activex/FooBarOcx.tlb
** from the type library ..\build\vc80\activex\FooBarOcx.tlb
**
****************************************************************************/

#ifndef QAX_DUMPCPP_FOOBAROCX_H
#define QAX_DUMPCPP_FOOBAROCX_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef FOOBAROCX_EXPORT
#define FOOBAROCX_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace

namespace FooBarOcx {

// forward declarations
    class IFoo;

class FOOBAROCX_EXPORT IFoo : public QAxObject
{
public:
    IFoo(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Method SayHello

    method SayHello

    */
    inline void SayHello();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class FOOBAROCX_EXPORT IBar : public QAxObject
{
public:
    IBar(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Method GetFoo

    method GetFoo

    */
    inline void GetFoo(FooBarOcx::IFoo** ppFoo);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class FOOBAROCX_EXPORT Foo : public QAxObject
{
public:
    Foo(QObject *parent = 0)
    : QAxObject(parent)
    {
        setControl(QStringLiteral("{0ed8df5e-58b8-4186-85a2-6211ebc9ba7e}"));
    }

    Foo(IFoo *iface)
    : QAxObject()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Method SayHello

    method SayHello

    */
    inline void SayHello();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class FOOBAROCX_EXPORT Bar : public QAxObject
{
public:
    Bar(QObject *parent = 0)
    : QAxObject(parent)
    {
        setControl(QStringLiteral("{500b5582-965c-4de9-a861-6ad75fdb1bf9}"));
    }

    Bar(IBar *iface)
    : QAxObject()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Method GetFoo

    method GetFoo

    */
    inline void GetFoo(FooBarOcx::IFoo** ppFoo);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_FOOBAROCX_NOINLINES
inline void Foo::SayHello()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}


inline void IFoo::SayHello()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}


inline void Bar::GetFoo(FooBarOcx::IFoo** ppFoo)
{
    void *_a[] = {0, (void*)&ppFoo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}


inline void IBar::GetFoo(FooBarOcx::IFoo** ppFoo)
{
    void *_a[] = {0, (void*)&ppFoo};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<FooBarOcx::Foo, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<FooBarOcx::Foo*>(t)->FooBarOcx::Foo::~Foo();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) FooBarOcx::Foo;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const FooBarOcx::Foo*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<FooBarOcx::Foo*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<FooBarOcx::IFoo, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<FooBarOcx::IFoo*>(t)->FooBarOcx::IFoo::~IFoo();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) FooBarOcx::IFoo;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const FooBarOcx::IFoo*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<FooBarOcx::IFoo*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<FooBarOcx::Bar, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<FooBarOcx::Bar*>(t)->FooBarOcx::Bar::~Bar();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) FooBarOcx::Bar;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const FooBarOcx::Bar*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<FooBarOcx::Bar*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<FooBarOcx::IBar, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<FooBarOcx::IBar*>(t)->FooBarOcx::IBar::~IBar();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) FooBarOcx::IBar;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const FooBarOcx::IBar*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<FooBarOcx::IBar*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

